'use strict'

import * as types from './types'

describe('user.types', function () {
  it('should export types', function () {
    expect(types).toEqual({
      IPFS_FETCH: 'IPFS_FETCH',
      IPFS_FETCH_COMPLETED: 'IPFS_FETCH_COMPLETED',
      IPFS_FETCH_FAILED: 'IPFS_FETCH_FAILED',
      IPFS_SETUP: 'IPFS_SETUP',
      IPFS_SETUP_COMPLETED: 'IPFS_SETUP_COMPLETED',
      IPFS_SETUP_FAILED: 'IPFS_SETUP_FAILED',
      IPFS_UPDATE: 'IPFS_UPDATE',
      IPFS_UPDATE_COMPLETED: 'IPFS_UPDATE_COMPLETED',
      IPFS_UPDATE_FAILED: 'IPFS_UPDATE_FAILED',
      IPFS_GETADDRESS: 'IPFS_GETADDRESS',
      IPFS_GETADDRESS_COMPLETED: 'IPFS_GETADDRESS_COMPLETED',
      IPFS_GETADDRESS_FAILED: 'IPFS_GETADDRESS_FAILED'

    })
  })
})
