export const CART_TOTAL = 'CART_TOTAL'
export const CART_TOTAL_COMPLETED = 'CART_TOTAL_COMPLETED'
export const CART_TOTAL_FAILED = 'CART_TOTAL_FAILED'

export const CART_FETCH = 'CART_FETCH'
export const CART_FETCH_COMPLETED = 'CART_FETCH_COMPLETED'
export const CART_FETCH_FAILED = 'CART_FETCH_FAILED'

export const ADD_ITEM = 'ADD_ITEM'
export const ADD_ITEM_COMPLETED = 'ADD_ITEM_COMPLETED'
export const ADD_ITEM_FAILED = 'ADD_ITEM_FAILED'

export const ITEM_UPDATE = 'ITEM_UPDATE'
export const ITEM_UPDATE_COMPLETED = 'ITEM_UPDATE_COMPLETED'
export const ITEM_UPDATE_FAILED = 'ITEM_UPDATE_FAILED'
