export const CART_TOTAL = 'CART_TOTAL'
export const CART_TOTAL_COMPLETED = 'CART_TOTAL_COMPLETED'
export const CART_TOTAL_FAILED = 'CART_TOTAL_FAILED'

export const CART_FETCH = 'CART_FETCH'
export const CART_FETCH_COMPLETED = 'CART_FETCH_COMPLETED'
export const CART_FETCH_FAILED = 'CART_FETCH_FAILED'

export const ITEM_REMOVE = 'ITEM_REMOVE'
export const ITEM_REMOVE_COMPLETED = 'ITEM_REMOVE_COMPLETED'
export const ITEM_REMOVE_FAILED = 'ITEM_REMOVE_FAILED'

export const ITEM_UPDATE = 'ITEM_UPDATE'
export const ITEM_UPDATE_COMPLETED = 'ITEM_UPDATE_COMPLETED'
export const ITEM_UPDATE_FAILED = 'ITEM_UPDATE_FAILED'
