export const IPFS_FETCH = 'IPFS_FETCH'
export const IPFS_FETCH_COMPLETED = 'IPFS_FETCH_COMPLETED'
export const IPFS_FETCH_FAILED = 'IPFS_FETCH_FAILED'

export const IPFS_SETUP = 'IPFS_SETUP'
export const IPFS_SETUP_COMPLETED = 'IPFS_SETUP_COMPLETED'
export const IPFS_SETUP_FAILED = 'IPFS_SETUP_FAILED'

export const IPFS_UPDATE = 'IPFS_UPDATE'
export const IPFS_UPDATE_COMPLETED = 'IPFS_UPDATE_COMPLETED'
export const IPFS_UPDATE_FAILED = 'IPFS_UPDATE_FAILED'

export const IPFS_GETADDRESS = 'IPFS_GETADDRESS'
export const IPFS_GETADDRESS_COMPLETED = 'IPFS_GETADDRESS_COMPLETED'
export const IPFS_GETADDRESS_FAILED = 'IPFS_GETADDRESS_FAILED'
