'use strict'

import * as types from './types'

describe('user.types', function () {
  it('should export types', function () {
    expect(types).toEqual({
      CLEAR_CART: 'CLEAR_CART',
      CLEAR_CART_COMPLETED: 'CLEAR_CART_COMPLETED',
      CLEAR_CART_FAILED: 'CLEAR_CART_FAILED',
      CART_TOTAL: 'CART_TOTAL',
      CART_TOTAL_COMPLETED: 'CART_TOTAL_COMPLETED',
      CART_TOTAL_FAILED: 'CART_TOTAL_FAILED',
      CART_FETCH: 'CART_FETCH',
      CART_FETCH_COMPLETED: 'CART_FETCH_COMPLETED',
      CART_FETCH_FAILED: 'CART_FETCH_FAILED',
      ADD_ITEM: 'ADD_ITEM',
      ADD_ITEM_COMPLETED: 'ADD_ITEM_COMPLETED',
      ADD_ITEM_FAILED: 'ADD_ITEM_FAILED',
      REMOVE_ITEM: 'REMOVE_ITEM',
      REMOVE_ITEM_COMPLETED: 'REMOVE_ITEM_COMPLETED',
      REMOVE_ITEM_FAILED: 'REMOVE_ITEM_FAILED'
    })
  })
})
